name = "onedark"

[dark]
fg = "#abb2bf"
bg = "#282c34"
cursor = "#61afef"
chrome = "#21252b"
border = "#3e4451"
buttons = ["#e06c75", "#e5c07b", "#98c379"]
ansi = [
  "#282c34", "#e06c75", "#98c379", "#e5c07b",
  "#61afef", "#c678dd", "#56b6c2", "#abb2bf",
  "#5c6370", "#e06c75", "#98c379", "#e5c07b",
  "#61afef", "#c678dd", "#56b6c2", "#ffffff",
]
